project:
  type: sverto
  
execute:
  freeze: auto

website:
  navbar:
    title: Sverto
    background: black
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Example: bar chart"
        file: examples/barchart/index.qmd
      # - about.qmd

format:
  sverto-html:
    title-block-banner: "#e1e4e6"
