project:
  type: sverto
  
execute:
  freeze: auto

website:
  navbar:
    logo: 360info-logo.png
    logo-href: https://github.com/360-info
    background: "#222222"
    search: true
    left:
      - text: "Sverto"
        file: index.qmd
      - text: "Examples"
        menu:
          - text: "Bar chart"
            file: examples/barchart/index.qmd
      # - about.qmd
    right:
      - icon: github
        href: https://github.com/360-info/sverto

format:
  sverto-html:
    title-block-banner: "#e1e4e6"
    theme: default
    linkcolor: "#36a7e9"
    
