on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install npm
        uses: actions/setup-node@v3

      - name: Install npm packages
        run: npm install
        working-directory: ./docs

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        path: docs
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}